---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
platforms:
  - name: instance-rocky
    image: docker.io/rockylinux/rockylinux:9.1
    pre_build_image: true
  - name: instance-rh
    image: registry.access.redhat.com/ubi9/ubi
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
